
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
#    -   id: fix-encoding-pragma
#    -   id: check-ast  # not very useful

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    # Run the linter.
    - id: ruff
    #  args: [ --fix ]
    # Run the formatter.
    #- id: ruff-format
